export enum ResultTableRequestsColumn {
  DATE = "DATE",
  ADDRESS = "ADDRESS",
  TYPE = "TYPE",
  ATTRIBUTES = "ATTRIBUTES",
  REQUEST_PRICE = "REQUEST_PRICE",
  CALCULATED_PRICE = "CALCULATED_PRICE",
  DEVIATION = "DEVIATION",
  STATUS = "STATUS",
  AUTHOR = "AUTHOR",
}
