export enum NavMenuButtons {
  FLAT_REPORTS = 1,
  LIVING_HOUSE_REPORTS = 2,
  LAST_ROOM_REPORTS = 3,
  COUNTRY_PROPERTY_REPORTS = 4,
  COMMERCIAL_REPORTS = 5,
  INTANGIBLE_REPORTS = 6,
  MOVABLE_REPORTS = 7,
  INVENTORY_REPORTS = 8,
  MIXED_REPORTS = 9,
  GARAGE_REPORTS = 10,
  VEHICLE_REPORTS = 11,
}
